# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: careinamo
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: home-proyect
# "service" is the name of this project. This will also be added to your AWS resource names.
service: home-proyect

stages:
  default:
    params:
      tableName: housekit-table-${sls:stage}
      clientsTableName: clients-housekit-table-${sls:stage}

provider:
  name: aws
  runtime: nodejs22.x
  region: ${opt:region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt UsersTable.Arn
  environment:
    UNIQUE_TABLE: ${param:tableName}
    CLIENTS_TABLE: clients-housekit-table-dev

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH # Partition key
          - AttributeName: SK
            KeyType: RANGE # Sort key
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}

    ClientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH # Partition key
          - AttributeName: SK
            KeyType: RANGE # Sort key
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:clientsTableName}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  listDevices:
    handler: functions/listDevices.listDevices
    events:
      - httpApi:
          path: /listDevices
          method: get

  updateDeviceStatus:
    handler: functions/updateDeviceStatus.updateDeviceStatus
    events:
      - httpApi:
          path: /updateDeviceStatus
          method: post
    iam:
      role:
        statements:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:UpdateItem
            Resource:
              - arn:aws:dynamodb:${self:provider.region}:*:table/${param:tableName}

  # ðŸ”¹ Nueva funciÃ³n ejecutada por EventBridge cada 15 minutos
  refreshToken:
    handler: functions/refreshToken.refreshToken
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          description: Ejecuta la funciÃ³n cada 5 minutos desde EventBridge
    iam:
      role:
        statements:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:UpdateItem
            Resource:
              - arn:aws:dynamodb:${self:provider.region}:*:table/${param:tableName}

  # ðŸ”¹ Nueva funciÃ³n para crear clientes
  createClient:
    handler: functions/clients/createClient.createClient
    events:
      - httpApi:
          path: /createClient
          method: post
    iam:
      role:
        statements:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource:
              - arn:aws:dynamodb:${self:provider.region}:*:table/${param:clientsTableName}